{% set name = "ansi2html" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3453bf87535d37b827b05245faaa756dbab4ec3d69925e352b6319c3c955c0a5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv
  entry_points:
    - ansi2html=ansi2html.converter:main
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=45.0.0
    - setuptools_scm >=7.0.0
  run:
    - python
    - importlib-metadata  # [py<38]
    - typing_extensions   # [py<38]

test:
  source_files:
    - tests
  imports:
    - ansi2html
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - ansi2html --help
    - ansi2html --version | grep -q {{ version }}
    - python -m pytest -ra tests

about:
  home: https://pypi.org/project/ansi2html
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Convert text with ANSI color codes to HTML or to LaTeX.
  description: |
    ansi2html allows users to convert text with ANSI color codes
    to HTML or to Latex.
  doc_url: https://ansi2html.readthedocs.io
  dev_url: https://github.com/pycontribs/ansi2html

extra:
  recipe-maintainers:
    - nehaljwani
