{% set name = "ansi2html" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c6837a13ecc1903aab7a545353312049dfedfe5105362ad3a8d9d207871ec71
  patches:
    - 0001-Fix-output-for-help.patch

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv
  entry_points:
    - ansi2html=ansi2html.converter:main

requirements:
  build:
    - m2-patch  # [win]
    - patch     # [unix]
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python
    - importlib-metadata  # [py<38]
    - typing_extensions   # [py<38]

test:
  source_files:
    - tests
  imports:
    - ansi2html
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -m pytest -ra tests
    - ansi2html --help
    - ansi2html --version | grep -q {{ version }}

about:
  home: https://pypi.org/project/ansi2html/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Convert text with ANSI color codes to HTML or to LaTeX.
  description: |
    ansi2html allows users to convert text with ANSI color codes
    to HTML or to Latex.
  doc_url: https://ansi2html.readthedocs.io/
  dev_url: https://github.com/pycontribs/ansi2html

extra:
  recipe-maintainers:
    - nehaljwani
