{% set name = "ansi2html" %}
{% set version = "1.8.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "38b82a298482a1fa2613f0f9c9beb3db72a8f832eeac58eb2e47bf32cd37f6d5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ file_ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  {{ hash_type }}: {{ hash_value }}

build:
  number: 0
  entry_points:
    - ansi2html=ansi2html.converter:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
    - setuptools 
    - setuptools_scm 6.0.1
    - setuptools_scm_git_archive 1.1
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - ansi2html
  commands:
    - pip check
    - nosetests tests/test_ansi2html.py
    - ansi2html --help
    - ansi2html --version | grep -q {{ version }}
  requires:
    - mock >=0.8
    - nose
    - pip

about:
  home: https://pypi.org/project/ansi2html/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Convert text with ANSI color codes to HTML or to LaTeX.
  description: |
    ansi2html allows users to convert text with ANSI color codes
    to HTML or to Latex.
  doc_source_url: https://github.com/pycontribs/ansi2html/blob/develop/README.rst
  dev_url: https://github.com/pycontribs/ansi2html

extra:
  recipe-maintainers:
    - nehaljwani
